# ----------------------------
# Makefile Options
# ----------------------------

NAME = BATTSHIP
#ICON = icon.png
DESCRIPTION = "Shoot each other!"
COMPRESSED = YES
COMPRESSED_MODE = zx0
HAS_PRINTF = NO
OUTPUT_MAP = NO
PREFER_OS_CRT = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)