# ----------------------------
# Makefile Options
# ----------------------------

NAME = TEST
#ICON = icon.png
DESCRIPTION = "TI-84 program test"
COMPRESSED = YES
COMPRESSED_MODE = zx0
HAS_PRINTF = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)