# ----------------------------
# Makefile Options
# ----------------------------
# formerly called RECALL, now called MATH

NAME = MATH
#ICON = icon.png
#DESCRIPTION = "Recall as many numbers as you can!"
DESCRIPTION = "Do some simple math!"
COMPRESSED = YES
COMPRESSED_MODE = zx0
HAS_PRINTF = NO
OUTPUT_MAP = NO
PREFER_OS_CRT = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)